.TH xsct 1 "December 2025" "2.4" "User Manual"
.SH NAME
xsct \- X11 set screen color temperature
.SH SYNOPSIS
.B xsct 
[options] 
.I [temperature]
.I [brightness]

.SH DESCRIPTION
.B xsct
sets the screen's color temperature.

.SH OPTIONS
.TP
.B -h, --help
Display usage information and exit
.TP
.B -v, --verbose
Display debugging information
.TP
.B -d, --delta
Shift temperature and brightness by temperature and brightness value
.TP
.B -s, --screen N
Zero-based index of screen to use.
.TP
.B -t, --toggle
Toggle between night and day temperature.
.TP
.B -c, --crtc N
Zero-based index of CRTC to use.
.TP
.B -e, --noenv
Ignore environment variables that affect the execution of \fBxsct\fR.
.TP
.B -N, --night
Set the color temperature to the night temperature of 4500
(unless changed by \fBXSCT_TEMPERATURE_NIGHT\fR).
The flag acts in place of the [temperature] argument,
unless it is followed by \fB-t\fR or \fB-d\fR flag,
in which case it will be ignored.
.TP
.B -D, --day
Set the color temperature to the day temperature of 6500
(unless changed by \fBXSCT_TEMPERATURE_DAY\fR).
This is equivalent to "\fBxsct 0\fR".
The flag acts in place of the [temperature] argument,
unless it is followed by \fB-t\fR or \fB-d\fR flag,
in which case it will be ignored.
.TP
.I [temperature]
Black body temperature
.br
If the value is 0, xsct sets the color temperature to the default of 6500
(or the value of the \fBXSCT_TEMPERATURE_DAY\fR).
.br
If no arguments are passed, xsct estimates the current display temperature and brightness
.TP
.I [brightness]
Linear brightness between 0.0 (inclusive) and 1.0 (inclusive). The default value is 1.0 if no parameter is passed.

.SH ENVIRONMENT VARIABLES
The following environment variables affect the execution of \fBxsct\fR.
.TP
.B XSCT_TEMPERATURE_DAY
Changes the default value of the \fIday\fR temperature.
Additionally when the value of \fI[temperature]\fR is specified as 0,
it will be set to this value instead.
.TP
.B XSCT_TEMPERATURE_NIGHT
Changes the default value of the \fInight\fR temperature.

.SH EXIT STATUS
xsct exits with an exit status of 0 on success and a non-zero value 0 on failure.

.SH AUTHOR
xsct is based on sct by Ted Unangst <tedu@openbsd.org>

.SH SEE ALSO
redshift(1), xtemp(1)
